name: Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Package Application
      run: |
        pip install pyinstaller
        pyinstaller --noconfirm --onefile --windowed --name "PDFWorker" main.py

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDFWorker
        path: dist/PDFWorker.exe
